### LabelEncoder

sklearn.preprocessing.LabelEncoder

>fit(y)

>fit_transform(y)

>get_params(deep=True)

>inverse_transform(y)

>set_params(**params)

>transform(y)


In [5]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
import numpy as np

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','믹서','믹서']

In [8]:
encoder = LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)

In [9]:
print('인코딩 변환값: ', labels)

인코딩 변환값:  [0 1 4 5 3 2 2]


In [10]:
print('인코딩 클래스: ', encoder.classes_)

인코딩 클래스:  ['TV' '냉장고' '믹서' '선풍기' '전자렌지' '컴퓨터']


In [11]:
print('디코딩 원본 값: ', encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본 값:  ['전자렌지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


### Titanic실습

In [12]:
import pandas as pd

In [13]:
train = pd.read_csv('C:/apps/ml/titanic_train.csv')

In [14]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
train.drop(columns=['PassengerId','Pclass','Name','SibSp','Parch','Ticket','Fare','Cabin','Embarked'])

Survived     Sex   Age
0           0    male  22.0
1           1  female  38.0
2           1  female  26.0
3           1  female  35.0
4           0    male  35.0
..        ...     ...   ...
886         0    male  27.0
887         1  female  19.0
888         0  female   NaN
889         1    male  26.0
890         0    male  32.0

[891 rows x 3 columns]

In [16]:
#결측치의 개수 확인
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [17]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
train['Sex'] = encoder.fit_transform(train['Age'])
train['Embarked'] = encoder.fit_transform(train['Embarked'])

In [18]:
train['Age'].isnull().sum()

177

In [19]:
train['Age']  = train['Age'].fillna(train['Age'].mean())

In [20]:
train['Embarked'] = train['Embarked'].fillna('S')

In [21]:
train['Embarked'].isnull().sum()

0

In [22]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris   28  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...   51  38.0      1      0   
2                             Heikkinen, Miss. Laina   34  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)   47  35.0      1      0   
4                           Allen, Mr. William Henry   47  35.0      0      0   

             Ticket     Fare Cabin  Embarked  
0         A/5 21171   7.2500   NaN         2  
1          PC 17599  71.2833   C85         0  
2  STON/O2. 3101282   7.9250   NaN         2  
3            113803  53.1000  C123         2  
4            373450   8.0500   NaN         2

### One Hot encoder

class sklearn.preprocessing.OneHotEncoder(*, categories='auto', drop=None, sparse=True, dtype=<class 'numpy.float64'>, handle_unknown='error', min_frequency=None, max_categories=None)

In [27]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [28]:
items = ['TV','냉장고','전자렌지','컴퓨터','선풍기','믹서','믹서']

In [29]:
#먼저 숫자값으로 변환을 위해 Label Encoder로 변홥합니다.
encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

In [38]:
#2차원 데이터로 변홥합니다. 2X1행 > 1행 X 2열로 바꿔줌
labels = labels.reshape(-1,1)

In [39]:
oh_encoder = OneHotEncoder()
data=oh_encoder.fit_transform(labels)

In [73]:
labels

array([[0],
       [1],
       [4],
       [5],
       [3],
       [2],
       [2]])

In [74]:
#원-핫 인코딩을 적용합니다.
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

In [75]:
print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코뎅 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코뎅 데이터 차원
(7, 6)


In [65]:
import pandas as pd

In [ ]:
df = pd.DataFrame({'item':['TV']})

### 타이타닉 파일 one hot Encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

### pandas.get_dummies

pandas.get_dummies(data, prefix=None, prefix_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)

In [23]:
import pandas as pd
df = pd.read_csv('C:/apps/ml/titanic_train.csv')

In [24]:
df.drop(columns = ['PassengerId','Pclass','Name','SibSp', 'Parch','Ticket','Fare','Cabin'],inplace=True)

In [25]:
df['Age']  = df['Age'].fillna(train['Age'].mean() )

In [26]:
df['Embarked'] = df['Embarked'].fillna('S')

In [27]:
data = df.loc[:, 'Embarked']

In [28]:
data

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [94]:
dummy_embark = pd.get_dummies(data)

In [96]:
dummy_data = pd.get_dummies(df[['Sex','Embarked']])

In [97]:
dummy_data

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [98]:
df

Survived     Sex        Age Embarked
0           0    male  22.000000        S
1           1  female  38.000000        C
2           1  female  26.000000        S
3           1  female  35.000000        S
4           0    male  35.000000        S
..        ...     ...        ...      ...
886         0    male  27.000000        S
887         1  female  19.000000        S
888         0  female  29.699118        S
889         1    male  26.000000        C
890         0    male  32.000000        Q

[891 rows x 4 columns]

In [116]:
#파일 합치기
dummy_df = pd.concat([df,dummy_data],axis=1)

In [117]:
dummy_df

Survived     Sex        Age Embarked  Sex_female  Sex_male  Embarked_C  \
0           0    male  22.000000        S           0         1           0   
1           1  female  38.000000        C           1         0           1   
2           1  female  26.000000        S           1         0           0   
3           1  female  35.000000        S           1         0           0   
4           0    male  35.000000        S           0         1           0   
..        ...     ...        ...      ...         ...       ...         ...   
886         0    male  27.000000        S           0         1           0   
887         1  female  19.000000        S           1         0           0   
888         0  female  29.699118        S           1         0           0   
889         1    male  26.000000        C           0         1           1   
890         0    male  32.000000        Q           0         1           0   

     Embarked_Q  Embarked_S  
0             0           1  
1             0           0  
2             0           1  
3             0           1  
4             0           1  
..          ...         ...  
886           0           1  
887           0           1  
888           0           1  
889           0           0  
890           1           0  

[891 rows x 9 columns]

In [114]:
#Sex, Embarked는 삭제
dummy_df.drop(columns=['Sex','Embarked'], inplace = True)

In [115]:
dummy_df

Survived        Age  Sex_female  Sex_male  Embarked_C  Embarked_Q  \
0           0  22.000000           0         1           0           0   
1           1  38.000000           1         0           1           0   
2           1  26.000000           1         0           0           0   
3           1  35.000000           1         0           0           0   
4           0  35.000000           0         1           0           0   
..        ...        ...         ...       ...         ...         ...   
886         0  27.000000           0         1           0           0   
887         1  19.000000           1         0           0           0   
888         0  29.699118           1         0           0           0   
889         1  26.000000           0         1           1           0   
890         0  32.000000           0         1           0           1   

     Embarked_S  
0             1  
1             0  
2             1  
3             1  
4             1  
..          ...  
886           1  
887           1  
888           1  
889           0  
890           0  

[891 rows x 7 columns]